name: GitHub Actions

on:
  push:
    branches: ["main","master"]
  pull_request:
    branches: ["main","master"]

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Link Checker (lychee)
      id: lychee
      uses: lycheeverse/lychee-action@v2
